export const icons = {
  'map.mathematical-analysis': import('./map/mathematical-analysis'),
  'map.combinatorics': import('./map/combinatorics'),
  'map.why': import('./map/why'),
  'map.trigonometry': import('./map/trigonometry'),
  'map.geometry': import('./map/geometry'),
  'map.formulas': import('./map/formulas'),
  'map.numbers-actions': import('./map/numbers-actions'),

  agent: import('./regular/agent'),
  arrow: import('./regular/arrow'),
  backspace: import('./regular/backspace'),
  bookAndHat: import('./regular/bookAndHat'),
  close: import('./regular/close'),
  cube: import('./regular/cube'),
  dot: import('./regular/dot'),
  energy: import('./regular/energy'),
  experience: import('./regular/experience'),
  heart: import('./regular/heart'),
  'heart-outline': import('./regular/heart-outline'),
  graphic: import('./regular/graphic'),
  idea: import('./regular/idea'),
  info: import('./regular/info'),
  lock: import('./regular/lock'),
  message: import('./regular/message'),
  notification: import('./regular/notification'),
  openedBook: import('./regular/openedBook'),
  question: import('./regular/question'),
  search: import('./regular/search'),
  solution: import('./regular/solution'),
  share: import('./regular/share'),
  share2: import('./regular/share-2'),
  'share-outline': import('./regular/share-outline'),
  star: import('./regular/star'),
  'star-outline': import('./regular/star-outline'),
  sum: import('./regular/sum'),
  tick: import('./regular/tick'),
  user: import('./regular/user'),
};

export default icons;
